apiVersion: apps/v1  # The API version to use
kind: Deployment     # The type of Kubernetes resource
metadata:            # Identifying information
  name: hello-deployment  # Name of your deployment
spec:                # Desired state of the deployment
  replicas: 3        # Number of pod replicas to maintain
  selector:          # How the Deployment finds Pods to manage
    matchLabels:
      app: hello     # Label selector that matches the Pod template
  template:          # Pod template specification
    metadata:
      labels:        # Labels to apply to the Pods
        app: hello
    spec:            # Pod specification
      containers:
      - name: nginx  # Container name
        image: nginx:latest  # Container image
        ports:
        - containerPort: 80  # Port the container exposes
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: html
        configMap:
          name: nginx-html
