apiVersion: v1        # Core Kubernetes API for Services
kind: Service         # Type of resource
metadata:
  name: hello-service # Name of your service
spec:
  type: NodePort      # Service type (exposes on cluster nodes)
  selector:
    app: hello        # Selects Pods with this label
  ports:
    - protocol: TCP   # Network protocol
      port: 80        # Service port (cluster-internal)
      targetPort: 80  # Pod port where traffic is sent
      